### ISSUE TITLE
xcode 6.3.1 - doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [orta/RedXcode#4]

**Comment by orta** [comment]
willing to bet https://github.com/orta/RedXcode/commit/4b0e5c8f2cb21252bd55dbd000f3870951cc6d5a fixes it

**Comment by gerchicov-bp** [comment]
what does this one string from plist actually do? It seems you just add some identifier only

**Comment by orta** [comment]
you have to say in your plugin what versions of Xcode you support, when new Xcode release come out all plugin authors have to add an extra string to the plist. I already had it in my pasteboard history from another plugin, so I just added it via the github webpage.

**Comment by gerchicov-bp** [comment]
It seems it still doesn't work. I tried both Alcatraz and build from your git. The only case when the red icon appears is when I press "run" for "RedXcode" project. If it works via this way only then it is not a plugin.

**Comment by orta** [comment]
This is a plugin for plugin developers, it only shows Red when Xcode is inside a debugger. It's a warning that the Xcode you're looking at is ephemeral. Do you have other expectations?

**Comment by gerchicov-bp** [comment]
I hoped it is run on every project debug. I have multiple versions of xcode and sometimes run 2 of them at once and so it could be useful to see which one is run.

**Comment by orta** [comment]
You're probably more interested in https://github.com/zats/BetaWarpaint.git

**Comment by gerchicov-bp** [comment]
No. It simply shows different icons for various xcode versions and doesn't allow to see which one is currently run. It doesn't even distinguish various versions (beta and normal versions only).
