### ISSUE TITLE
Debugged Xcode crashes on launch if ‘View Debugging’ is enabled.

### ISSUE THREAD

**Issue by alloy** [orta/RedXcode#9]
Not sure if this is a known thing or if it’s supposed to work but isn’t for me, but I had to disable ‘View Debugging’ from the scheme’s debugging options, otherwise Xcode would crash on startup.

The project of RedXcode has this disabled as well, which makes me think it’s a known thing? In which case it would be nice to tell users about such configuration in the README.

**Comment by orta** [comment]
Known issue with Xcode, maybe could be ficed in the new plugin template?

**Comment by alloy** [comment]
That’s a good idea, but it doesn’t retroactively help those that already have plugin projects, so if this is an issue that’s going to stay around, I think it should be mentioned in the README.

**Comment by alloy** [comment]
Interestingly enough that is already the setting in the Xcode plugin template, I guess I must have done some shenanigans with targets and schemes and ended up creating a new scheme.

**Comment by orta** [comment]
>  I think it should be mentioned in the README.

I agree with this
